Repository KooKim2Jung/DodamDodam, pull requests merged in 2024-07, with the labels that each got.

#202 [FEAT] 디테일 페이지에 가로형 Swiper 슬라이더 적용
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Detail/DetailForm.js
  frontend/src/components/detail/conversationsummary/ConversationSummary.js
  frontend/src/components/detail/emotionalanalysis/EmotionalAnalysis.js
  frontend/src/components/detail/scheduling/Scheduling.js
  frontend/src/components/detail/settings/Settings.js
  frontend/src/components/section/footer/FooterForm.js
  frontend/src/components/section/header/UserHeaderForm.js
  frontend/src/index.css
  frontend/src/pages/Main/Detail/EmotionalAnalysisPage.js
  frontend/src/pages/Main/Detail/SettingsPage.js
  frontend/src/pages/main/detail/Detail.css
  frontend/src/pages/main/detail/DetailPage.js
Labels: 기능구현, 리팩토링

#203 [FEAT] 메인 페이지에 세로형 Swiper 슬라이더 적용
  frontend/public/images/camera.png
  frontend/public/images/circle.png
  frontend/public/images/clock.png
  frontend/public/images/dodam_angry.png
  frontend/public/images/dodam_anxious.png
  frontend/public/images/dodam_basic.png
  frontend/public/images/dodam_circle.png
  frontend/public/images/dodam_embarrassed.png
  frontend/public/images/dodam_happy.png
  frontend/public/images/dodam_hurt.png
  frontend/public/images/dodam_sad.png
  frontend/public/images/dodam_signup.png
  frontend/public/images/flower.png
  frontend/public/images/love.png
  frontend/public/images/orange_star.png
  frontend/public/images/setting.png
  frontend/public/images/speechbubble.png
  frontend/public/images/spinner.gif
  frontend/public/images/star.png
  frontend/src/App.js
  frontend/src/components/Spinner/Spinner.js
  frontend/src/components/Ward/SpeechToText.js
  frontend/src/components/guardian/conversation/ConversationContentBoard.js
  frontend/src/components/guardian/emotionAnalysis/EmotionAnalysisGraph.js
  frontend/src/components/guardian/wardSettings/WardSettingsForm.js
  frontend/src/components/main/about/About.js
  frontend/src/components/main/detail/Detail.css
  frontend/src/components/main/detail/Detail.js
  frontend/src/components/main/detail/DetailForm.js
  frontend/src/components/main/detail/conversationsummary/ConversationSummary.js
  frontend/src/components/main/detail/emotionalanalysis/EmotionalAnalysis.js
  frontend/src/components/main/detail/scheduling/Scheduling.js
  frontend/src/components/main/detail/settings/Settings.js
  frontend/src/components/main/start/Start.js
  frontend/src/components/section/aside/AsideForm.js
  frontend/src/components/section/footer/FooterForm.js
  frontend/src/components/section/header/NonUserHeaderForm.js
  frontend/src/components/section/header/UserHeaderForm.js
  frontend/src/pages/Guardian/DodamSettings/DodamSettingsPage.js
  frontend/src/pages/Main/MainPage.js
  frontend/src/pages/main/Main.css
  frontend/src/pages/main/detail/DetailPage.js
  frontend/src/pages/main/flower.png
  frontend/tailwind.config.js
Labels: 기능구현, 리팩토링

#204 [REFACTOR] 회원가입, 로그인 API 코드 수정 && Tailwind CSS 수정
  frontend/public/images/dodam_signup.png
  frontend/src/components/Guardian/GuardianModeModalForm.js
  frontend/src/components/Wave.css
  frontend/src/components/guardian/wardSettings/WardSettingsForm.js
  frontend/src/components/main/start/Start.js
  frontend/src/components/user/login/LoginCheck.js
  frontend/src/components/user/login/LoginForm.js
  frontend/src/components/user/signup/SignupCheck.js
  frontend/src/components/user/signup/SignupForm.js
  frontend/src/index.css
  frontend/src/pages/user/login/LoginPage.js
  frontend/src/pages/user/signup/SignupPage.js
  frontend/tailwind.config.js
Labels: 리팩토링

#208 [FEAT] React Context API 사용
  frontend/src/App.js
  frontend/src/components/section/header/HeaderForm.js
  frontend/src/index.js
  frontend/src/pages/Guardian/DodamSettings/DodamSettingsPage.js
  frontend/src/pages/Guardian/Schedule/SchedulePage.js
  frontend/src/pages/Guardian/ViewConversation/ViewConversationPage.js
  frontend/src/pages/Guardian/ViewEmotionAnalysis/ViewEmotionAnalysisPage.js
  frontend/src/pages/Guardian/WardSettings/WardSettingsPage.js
  frontend/src/pages/Ward/WardPage.js
  frontend/src/pages/main/small_flower.png
  frontend/src/pages/user/login/LoginPage.js
Labels: 기능구현

#214 Refactor/#176
  fastapi/conversations/gpt_model_utility.py
  fastapi/poetry.lock
Labels: 리팩토링
